services:
  db:
    container_name: h0-mongo
    image: mongo:7
    environment:
      TZ: ${TZ}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${DOCKER_PATH}/mongodb/data:/data/db
    ports:
      - "${MONGO_PORT}:27017"   # expuesto para Tailscale
    restart: unless-stopped
    networks:
      - mongo-net

  mongo-express:
    container_name: h0-mongo-express
    image: mongo-express:latest
    depends_on:
      - db
    environment:
      TZ: ${TZ}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    restart: unless-stopped
    networks:
      - mongo-net

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DOCKER_PATH}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    user: "0:0"
    ports:
      - "8082:80"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    volumes:
      - ${DOCKER_PATH}/pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

networks:
  mongo-net:
    driver: bridge
