apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-next
  namespace: template-next
  labels:
    app: template-next
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: template-next
  template:
    metadata:
      labels:
        app: template-next
    spec:
      containers:
        - name: template-next
          image: ghcr.io/ismola/template-next:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 25m
              memory: 192Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 300m
              memory: 384Mi
              ephemeral-storage: 512Mi
