apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: stable-proxies
spec:
  statefulSet:
    pod:
      priorityClassName: homelab-critical
      nodeSelector:
        capability.isma.dev/stable: "true"
      tailscaleContainer:
        env:
          - name: TS_DEBUG_MTU
            value: "1150"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
