apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-hider
  namespace: zip-hider
  labels:
    app: zip-hider
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: zip-hider
  template:
    metadata:
      labels:
        app: zip-hider
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: isma.dev/ram-gb
                    operator: In
                    values: ["1"]
      containers:
        - name: zip-hider
          image: ghcr.io/ismola/zip-hider:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
              ephemeral-storage: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 256Mi
