apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
images:
  - name: ghcr.io/ismola/zip-hider
    newTag: main
    newName: ghcr.io/ismola/zip-hider
    digest: sha256:13b2689711697b334807b2994c446315f29d739b9c87bc976aa32cccfab223d4
