apiVersion: apps/v1
kind: Deployment
metadata:
  name: sj-wedding
  namespace: sj-wedding
  labels:
    app: sj-wedding
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: sj-wedding
  template:
    metadata:
      labels:
        app: sj-wedding
    spec:
      containers:
        - name: sj-wedding
          image: ghcr.io/ismola/s-j-wedding:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "80"
            - name: MONGO_DB_NAME
              value: "sj_wedding"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: sj-wedding-secrets
                  key: MONGO_URI
          resources:
            requests:
              cpu: 25m
              memory: 192Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 300m
              memory: 384Mi
              ephemeral-storage: 512Mi
