apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
images:
  - name: ghcr.io/ismola/s-j-wedding
    newTag: main
    newName: ghcr.io/ismola/s-j-wedding
    digest: sha256:28acfb891f6583e8ba132715045a66997c7c828d39e2994834ef2f079a2ab170
