apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
images:
  - name: ghcr.io/ismola/s-j-wedding
    newTag: main
    newName: ghcr.io/ismola/s-j-wedding
    digest: sha256:a79d94d60662754847df145d67803137409e7f71487d90fe731f3431b35d2d34
