all:
  vars:
    ansible_user: root
    ansible_become: false

  children:
    production:
      children:
        prod_k3s_server:
          hosts:
            prod_cp1:
              ansible_host: v3.elver-chicken.ts.net

        prod_rancher_node:
          hosts:
            prod_rancher1:
              ansible_host: rancher.elver-chicken.ts.net

        prod_k3s_workers:
          hosts:
            prod_worker1:
              ansible_host: v1.elver-chicken.ts.net
            prod_worker2:
              ansible_host: v2.elver-chicken.ts.net
            prod_worker3:
              ansible_host: v4.elver-chicken.ts.net

    staging:
      children:
        stg_k3s_server:
          hosts:
            stg_cp1:
              ansible_host: ubuntu3.elver-chicken.ts.net

        stg_rancher_node:
          hosts:
            stg_rancher1:
              ansible_host: rancher.elver-chicken.ts.net

        stg_k3s_workers:
          hosts:
            stg_worker1:
              ansible_host: ubuntu1.elver-chicken.ts.net
            stg_worker2:
              ansible_host: ubuntu4.elver-chicken.ts.net

    k3s_server:
      children:
        prod_k3s_server:
        stg_k3s_server:

    rancher_node:
      children:
        prod_rancher_node:
        stg_rancher_node:

    k3s_workers:
      children:
        prod_k3s_workers:
        stg_k3s_workers: