all:
  vars:
    ansible_user: root
    ansible_become: false

  children:
    production:
      children:
        # VM 24 GB RAM
        prod_k3s_server:
          hosts:
            prod_cp1:
              ansible_host: v3.elver-chicken.ts.net
        # VM 3 GB RAM TODO crear en vm
        # prod_rancher_node:
        #   hosts:
        #     prod_rancher1:
        #       ansible_host: rancher.elver-chicken.ts.net

        # 1 GB de RAM
        prod_k3s_workers:
          hosts:
            prod_worker1:
              ansible_host: v1.elver-chicken.ts.net
            prod_worker2:
              ansible_host: v2.elver-chicken.ts.net
            prod_worker4:
              ansible_host: v4.elver-chicken.ts.net
            prod_worker5:
              ansible_host: v5.elver-chicken.ts.net
            prod_worker6:
              ansible_host: v6.elver-chicken.ts.net
    # VM
    staging:
      children:
        # 3 GB RAM
        stg_k3s_server:
          hosts:
            stg_cp3:
              ansible_host: vm3.elver-chicken.ts.net

          # 4GB RAM
        stg_rancher_node:
          hosts:
            stg_rancher1:
              ansible_host: vm5.elver-chicken.ts.net

          # 1 GB RAM
        stg_k3s_workers:
          hosts:
            stg_worker1:
              ansible_host: vm1.elver-chicken.ts.net
            stg_worker4:
              ansible_host: vm4.elver-chicken.ts.net

    k3s_server:
      children:
        prod_k3s_server:
        stg_k3s_server:

    rancher_node:
      children:
        prod_rancher_node:
        stg_rancher_node:

    k3s_workers:
      children:
        prod_k3s_workers:
        stg_k3s_workers:
