all:
  children:
    production:
      vars:
        env: production
      hosts:
        prod_cp1:
          ansible_host: v3.elver-chicken.ts.net
          role: k3s_server
          provider: oracle
          ram_gb: 24
          cpu: 4
          arch: arm64
          distro: ubuntu

        prod_worker1:
          ansible_host: v1.elver-chicken.ts.net
          role: k3s_worker
          provider: oracle
          ram_gb: 1
          cpu: 1
          arch: amd64
          distro: ubuntu

        prod_worker2:
          ansible_host: v2.elver-chicken.ts.net
          role: k3s_worker
          provider: oracle
          ram_gb: 1
          cpu: 1
          arch: amd64
          distro: ubuntu

        prod_worker4:
          ansible_host: v4.elver-chicken.ts.net
          role: k3s_worker
          provider: google
          ram_gb: 1
          cpu: 1
          arch: amd64
          distro: debian

        prod_worker5:
          ansible_host: v5.elver-chicken.ts.net
          role: k3s_worker
          provider: oracle
          ram_gb: 1
          cpu: 1
          arch: amd64
          distro: ubuntu

        prod_worker6:
          ansible_host: v6.elver-chicken.ts.net
          role: k3s_worker
          provider: oracle
          ram_gb: 1
          cpu: 1
          arch: amd64
          distro: ubuntu

        prod_worker_rpi:
          ansible_host: rpi.elver-chicken.ts.net
          role: k3s_worker
          provider: homelab
          ram_gb: 2
          cpu: 4
          arch: arm64
          distro: debian

    staging:
      vars:
        env: staging
      hosts:
        stg_cp3:
          ansible_host: vm3.elver-chicken.ts.net
          role: k3s_server
          provider: vmware
          ram_gb: 3
          cpu: 1
          arch: amd64
          distro: ubuntu

        stg_rancher1:
          ansible_host: vm5.elver-chicken.ts.net
          role: rancher_node
          provider: vmware
          ram_gb: 4
          cpu: 1
          arch: amd64
          distro: ubuntu

        stg_worker1:
          ansible_host: vm1.elver-chicken.ts.net
          role: k3s_worker
          provider: vmware
          ram_gb: 1
          cpu: 1
          arch: amd64
          distro: ubuntu

        stg_worker4:
          ansible_host: vm4.elver-chicken.ts.net
          role: k3s_worker
          provider: vmware
          ram_gb: 1
          cpu: 1
          arch: amd64
          distro: ubuntu

    k3s_server:
      hosts:
        prod_cp1:
        stg_cp3:

    k3s_workers:
      hosts:
        prod_worker1:
        prod_worker2:
        prod_worker4:
        prod_worker5:
        prod_worker6:
        prod_worker_rpi:
        stg_worker1:
        stg_worker4:

    rancher_node:
      hosts:
        stg_rancher1: