apiVersion: apps/v1
kind: Deployment
metadata:
  name: cakeshop-concept
  namespace: cakeshop-concept
  labels:
    app: cakeshop-concept
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: cakeshop-concept
  template:
    metadata:
      labels:
        app: cakeshop-concept
    spec:
      containers:
        - name: cakeshop-concept
          image: ghcr.io/ismola/cakeshop-concept:main
          imagePullPolicy: Always
          ports:
            - containerPort: 4321
