apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/cakeshop-concept
    newTag: main
    newName: ghcr.io/ismola/cakeshop-concept
    digest: sha256:96ec2a01972c60e3ca4f1d01f30847b49c7f098a37b0b3739acd2161dbf3ebb0
