version: "2.1"

services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=10
      - TZ=Europe/Madrid
    volumes:
      - ${DOCKER_PATH}/heimdall:/config
    ports:
      - 9001:80
      # - 40443:443
    restart: unless-stopped
    
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
    restart: unless-stopped
