include:
  - path: ./cloudflare/compose.yml
  - path: ./media/compose.yml
  - path: ./networking/compose.yml
  - path: ./immich/compose.yml
  - path: ./opencloud/compose.yml
  - path: ./duplicati/compose.yml
  - path: ./gickup/compose.yml
  - path: ./pgbackup/compose.yml
  - path: ./minio/compose.yml
