apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - service-headless.yaml
  - service.yaml
  - service-tailscale.yaml
  - statefulset.yaml
  - exporter.yaml
  - pgadmin.yaml
  - pgadmin-httproute.yaml
  - pgadmin-ingress-tailscale.yaml
