apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/apple-concept
    newTag: main
    newName: ghcr.io/ismola/apple-concept
    digest: sha256:2b8334cc8ef3751a1c80fb83f1373239c76d31755291447350b5ab1719fe46db
