apiVersion: apps/v1
kind: Deployment
metadata:
  name: gott-calculator
  namespace: gott-calculator
  labels:
    app: gott-calculator
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: gott-calculator
  template:
    metadata:
      labels:
        app: gott-calculator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: capability.isma.dev/lightweight
                    operator: In
                    values: ["true"]
      containers:
        - name: gott-calculator
          image: ghcr.io/ismola/gott-calculator:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
              ephemeral-storage: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 256Mi
