apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/gott-calculator
    newTag: main
    newName: ghcr.io/ismola/gott-calculator
    digest: sha256:085c311dc4b0ec07693325e6b59acf6810f50f5d6ed740eabedc92040b0a6c21
