apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/gott-calculator
    newTag: main
    newName: ghcr.io/ismola/gott-calculator
    digest: sha256:f088d0e8d2a3dea7492ffce5e6a2bcb363f0a5556e39ab82859d75668df9e33f
