apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calendar-subscription-hub
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  namespaceSelector:
    matchNames:
      - calendar-subscription-hub
  selector:
    matchLabels:
      app: calendar-subscription-hub-web
  endpoints:
    - port: http
      path: /api/metrics
      interval: 30s
      scrapeTimeout: 10s
