apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-cloudflare
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik

  rules:
    - host: grafana.ismola.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-grafana"
                port:
                  number: 80