apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/ismola/japon-landing-concept
    newTag: main
    newName: ghcr.io/ismola/japon-landing-concept
    digest: sha256:b21e73f7c14b3dc7c8ad240bc2ee10803a01d8cbcb6160ac5dbbc3e3e1fd6190
