apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-snake
  namespace: js-snake
  labels:
    app: js-snake
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: js-snake
  template:
    metadata:
      labels:
        app: js-snake
    spec:
      containers:
        - name: js-snake
          image: ghcr.io/ismola/js-snake:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
