apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/js-snake
    newTag: main
    newName: ghcr.io/ismola/js-snake
    digest: sha256:d2219a5c38805011c9bb27640365ccc7226bb5d4a0d40cd03a3d9bee99f34469
