apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/js-snake
    newTag: main
    newName: ghcr.io/ismola/js-snake
    digest: sha256:94fc9238293e010df48fb4fff628f9137705f49eccf5c71db4c89ef87076ad32
