apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: homelab-image-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: git:secret:argocd/git-creds
    gitConfig:
      repository: https://github.com/Ismola/homelab.git
      branch: main
      writeBackTarget: kustomization

  commonUpdateSettings:
    updateStrategy: digest
    forceUpdate: false

  applicationRefs:
    - namePattern: portfolio
      useAnnotations: false
      images:
        - alias: portfolio
          imageName: ghcr.io/ismola/personal-portfolio:master
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/personal-portfolio

    - namePattern: zip-hider
      useAnnotations: false
      images:
        - alias: ziphider
          imageName: ghcr.io/ismola/zip-hider:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/zip-hider
    - namePattern: trivial-php
      useAnnotations: false
      images:
        - alias: trivialphp
          imageName: ghcr.io/ismola/trivial-php:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/trivial-php

    - namePattern: african-art-exhibition-concept
      useAnnotations: false
      images:
        - alias: africanartexhibitionconcept
          imageName: ghcr.io/ismola/african-art-exhibition-concept:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/african-art-exhibition-concept

    - namePattern: apple-concept
      useAnnotations: false
      images:
        - alias: appleconcept
          imageName: ghcr.io/ismola/apple-concept:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/apple-concept

    - namePattern: cakeshop-concept
      useAnnotations: false
      images:
        - alias: cakeshopconcept
          imageName: ghcr.io/ismola/cakeshop-concept:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/cakeshop-concept

    - namePattern: calendar-subscription-hub
      useAnnotations: false
      images:
        - alias: asismetro
          imageName: ghcr.io/ismola/asismetro-automations:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/asismetro-automations

        - alias: web
          imageName: ghcr.io/ismola/calendar-subscription-hub-web:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/calendar-subscription-hub-web

        - alias: worker
          imageName: ghcr.io/ismola/calendar-subscription-hub-worker:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/calendar-subscription-hub-worker

    - namePattern: gott-calculator
      useAnnotations: false
      images:
        - alias: gottcalculator
          imageName: ghcr.io/ismola/gott-calculator:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/gott-calculator

    - namePattern: japon-landing-concept
      useAnnotations: false
      images:
        - alias: japonlandingconcept
          imageName: ghcr.io/ismola/japon-landing-concept:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/japon-landing-concept

    - namePattern: js-snake
      useAnnotations: false
      images:
        - alias: jssnake
          imageName: ghcr.io/ismola/js-snake:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/js-snake

    - namePattern: jw-hitster
      useAnnotations: false
      images:
        - alias: jwhitster
          imageName: ghcr.io/ismola/jw-hitster:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/jw-hitster

    - namePattern: pro-login-animacion
      useAnnotations: false
      images:
        - alias: prologinanimacion
          imageName: ghcr.io/ismola/pro-login-animacion:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/pro-login-animacion

    - namePattern: sj-wedding
      useAnnotations: false
      images:
        - alias: sjwedding
          imageName: ghcr.io/ismola/s-j-wedding:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/s-j-wedding

    - namePattern: template-next
      useAnnotations: false
      images:
        - alias: templatenext
          imageName: ghcr.io/ismola/template-next:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/template-next

    - namePattern: "headlamp"
      useAnnotations: false
      writeBackConfig:
        method: git
        gitConfig:
          branch: main
          writeBackTarget: kustomization
      images:
        - alias: headlamp
          imageName: ghcr.io/headlamp-k8s/headlamp
          commonUpdateSettings:
            updateStrategy: semver
            forceUpdate: false
            allowTags: 'regexp:^v[0-9]+\.[0-9]+\.[0-9]+$'
          manifestTargets:
            kustomize:
              name: ghcr.io/headlamp-k8s/headlamp
    
    - namePattern: "open-date"
      useAnnotations: false
      images:
        - alias: templatenext
          imageName: ghcr.io/ismola/open-date:main
          manifestTargets:
            kustomize:
              name: ghcr.io/ismola/open-date
