apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/pro-login-animacion
    newTag: main
    newName: ghcr.io/ismola/pro-login-animacion
    digest: sha256:4ea3d3c1cc6679f303d8f3b849addf85f182c3b5c704feeacc98c14651520c72
