apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/pro-login-animacion
    newTag: main
    newName: ghcr.io/ismola/pro-login-animacion
    digest: sha256:d8777a36f39f3342fa7d2ede62447a399b34c02821eb4093ad1e99dd4ea7a638
