apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: pro-login-animacion
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 64Mi
        ephemeral-storage: 64Mi
      default:
        cpu: 300m
        memory: 384Mi
        ephemeral-storage: 512Mi
      min:
        cpu: 5m
        memory: 8Mi
        ephemeral-storage: 16Mi
      max:
        cpu: "2"
        memory: 2Gi
        ephemeral-storage: 4Gi
