argo-cd:
  global:
    domain: argocd.ismola.dev
    priorityClassName: homelab-critical
    nodeSelector:
      kubernetes.io/os: linux
      capability.isma.dev/stable: "true"

  configs:
    params:
      server.insecure: true
