apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw-hitster
  namespace: jw-hitster
  labels:
    app: jw-hitster
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: jw-hitster
  template:
    metadata:
      labels:
        app: jw-hitster
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: capability.isma.dev/general
                    operator: In
                    values: ["true"]
      containers:
        - name: jw-hitster
          image: ghcr.io/ismola/jw-hitster:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 25m
              memory: 192Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 300m
              memory: 384Mi
              ephemeral-storage: 512Mi
