apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/jw-hitster
    newTag: main
    newName: ghcr.io/ismola/jw-hitster
    digest: sha256:9c9eebababf694fea103821154eafec4baa32e58a110689467b04fe154ae5fee
