apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/jw-hitster
    newTag: main
    newName: ghcr.io/ismola/jw-hitster
    digest: sha256:e70a3b87cb4b8ae70934718a93c6a1fbe75cab15b05a875ea88e924648eaeea1
