apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/jw-hitster
    newTag: main
    newName: ghcr.io/ismola/jw-hitster
    digest: sha256:e7424f94f45dc66f608e9bec6cd543b5a12ce523ee3bd042bd04148f604dbad8
