apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-gateway-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 34.5.0
    helm:
      releaseName: traefik-gateway
      valuesObject:
        providers:
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
        gateway:
          enabled: false
        ingressClass:
          enabled: false
        priorityClassName: homelab-critical
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
