apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/ismola/personal-portfolio
    newTag: master
    newName: ghcr.io/ismola/personal-portfolio
    digest: sha256:32e6306719c169845b1a11defbff117d067ccfafb91030561e044d992fc90323
