apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/personal-portfolio
    newTag: master
    newName: ghcr.io/ismola/personal-portfolio
    digest: sha256:3d08df1c2129f9bdb3b5318c4de8e1498360ea7004ef09909a59c01f00d448ff
