apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/ismola/trivial-php
    newTag: main
    newName: ghcr.io/ismola/trivial-php
    digest: sha256:34566666dc90fad768f5ae489353c6e8e6b0ab84fe5fda61ef1cac51a47d03e3
