apiVersion: apps/v1
kind: Deployment
metadata:
  name: african-art-exhibition-concept
  namespace: african-art-exhibition-concept
  labels:
    app: african-art-exhibition-concept
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: african-art-exhibition-concept
  template:
    metadata:
      labels:
        app: african-art-exhibition-concept
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: capability.isma.dev/lightweight
                    operator: In
                    values: ["true"]
      containers:
        - name: african-art-exhibition-concept
          image: ghcr.io/ismola/african-art-exhibition-concept:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
              ephemeral-storage: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 256Mi
