apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/asismetro-automations
    newTag: main
    newName: ghcr.io/ismola/asismetro-automations
    digest: sha256:6f0ac9f8e07cfa2f6e76359fde1b3b71b52c3abef1bf4e03a82540e81f095475
  - name: ghcr.io/ismola/calendar-subscription-hub-web
    newTag: main
    newName: ghcr.io/ismola/calendar-subscription-hub-web
    digest: sha256:9e23e6a60c21c4a0eca7d0922efcfa6aa1ecc6e964cdcacddc0455ef67f396c8
  - name: ghcr.io/ismola/calendar-subscription-hub-worker
    newTag: main
    newName: ghcr.io/ismola/calendar-subscription-hub-worker
    digest: sha256:b7895eee6bd3492e2c3c0334cb81c99561ce766d48cec18f40bfe9b3902ca198
