apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/asismetro-automations
    newTag: main
    newName: ghcr.io/ismola/asismetro-automations
    digest: sha256:6f0ac9f8e07cfa2f6e76359fde1b3b71b52c3abef1bf4e03a82540e81f095475
  - name: ghcr.io/ismola/calendar-subscription-hub-web
    newTag: main
    newName: ghcr.io/ismola/calendar-subscription-hub-web
    digest: sha256:5dd4caf669847c9986b042ca0149922414ebe5d288fc6f46fad632ac4a80b82b
  - name: ghcr.io/ismola/calendar-subscription-hub-worker
    newTag: main
    newName: ghcr.io/ismola/calendar-subscription-hub-worker
    digest: sha256:9d8aaf2ad0d683829e88d6087fbaafb0dab498f280fb095f3992fb77468151c0
