apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: ghcr.io/ismola/asismetro-automations
    newTag: main
    newName: ghcr.io/ismola/asismetro-automations
    digest: sha256:45baf35578c17292a6491a26e7820bc4f65e7fed02ac3f4a596d6dad8f1dd2ce
  - name: ghcr.io/ismola/calendar-subscription-hub-web
    newTag: main
    newName: ghcr.io/ismola/calendar-subscription-hub-web
    digest: sha256:0544d0e7b5c845ad92872b2d24442481ccef5ea092e7410d1bb61deddfbb4407
  - name: ghcr.io/ismola/calendar-subscription-hub-worker
    newTag: main
    newName: ghcr.io/ismola/calendar-subscription-hub-worker
    digest: sha256:af9036e74971d9a8acd7671cbb0c6d22cb3e53ae3ecc6cef8ccdd5f79f123ee3
