apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/open-date
    newTag: main
    newName: ghcr.io/ismola/open-date
    digest: sha256:d77e881330bf730401d9fa291e1014f49e6a0bbc35928a944688e9f4cc697faf
