apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/open-date
    newTag: main
    newName: ghcr.io/ismola/open-date
    digest: sha256:6630f0a9ceed504a1b77dd509e1ae1fced7c3c34d10550af6316f01bdc0f2166
