apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - limitrange.yaml
  - hpa.yml
images:
  - name: ghcr.io/ismola/open-date
    newTag: main
    newName: ghcr.io/ismola/open-date
    digest: sha256:f39c3ce4fa35f95309212d9d1c4784b1b61d5bc7fb4075ba5df5e7307f988792
