---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=10
      - TZ=Europe/Madrid
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
      - CLI_ARGS= #optional
    volumes:
      - ${DOCKER_PATH}/duplicati/config:/config
      - /mnt/@usb/sda1/Volumen1/backups:/backups
      - /volume1:/source
    expose:
      - 8200
    restart: unless-stopped
